#!/bin/bash
#PBS -N pico-nonpareil-jianshu
#PBS -l nodes=1:ppn=64
#PBS -l mem=32gb
#PBS -l walltime=120:00:00
#PBS -q microcluster
#PBS -o /nv/hmicro1/jzhao399/scratch/log/pico/${PBS_JOBNAME}_${PBS_JOBID}.out
#PBS -e /nv/hmicro1/jzhao399/scratch/log/pico/${PBS_JOBNAME}_${PBS_JOBID}.err
#PBS -t 127,131,132,244,245,247,264-266,281,282,284,304,497,539,540,550-552


module load ncbi_blast/2.2.29
module load hmmer/3.0
module load mafft/7.245
module load usearch_64/7.0.1001

#VARIABLES
name=pico${PBS_ARRAYID}
wd=/nv/hmicro1/jzhao399/scratch/05.trimmedFastA
reads1=${wd}/${name}.1.tag.fasta
reads2=${wd}/${name}.2.tag.fasta
outdir=/nv/hmicro1/jzhao399/scratch/15A.nonpareil

/nv/hmicro1/jzhao399/shared3/apps/nonpareil/nonpareil -s ${reads2} -T kmer -b ${outdir}/${name}.2.nonpareil -t 64
