#!/bin/bash
#PBS -N gene_prediction_annotation
#PBS -l mem=24gb
#PBS -l nodes=1:ppn=24
#PBS -l walltime=12:00:00
#PBS -q microcluster
#PBS -o /nv/hmicro1/jzhao399/scratch/log/pico/${PBS_JOBNAME}_${PBS_JOBID}.out
#PBS -e /nv/hmicro1/jzhao399/scratch/log/pico/${PBS_JOBNAME}_${PBS_JOBID}.err
#PBS -t 127,131,132,244,245,247,264-266,281,282,284,304,497,539,540,550-552

module purge


name=pico${PBS_ARRAYID}
wd=/nv/hmicro1/jzhao399/gbrandt6/projects/pico/reads/06.megahitAssembly/${name}
output=/nv/hmicro1/jzhao399/scratch/17.prokka/${name}


source ~/.bashrc
conda init bash
conda activate base

~/data/miniconda3/bin/prokka --outdir ${output} --force --prefix ${name} --addgenes --gffver 3 --compliant --kingdom Bacteria --gcode 11 --evalue 1e-9 --metagenome --cpus 24 ${wd}/${name}.contigs.long.fa
