#!/bin/bash
#PBS -N MAG-abudance-miguel-bedtools-coverage
#PBS -l mem=24gb
#PBS -l nodes=1:ppn=24
#PBS -l walltime=48:00:00
#PBS -q biocluster-6
#PBS -o /nv/hmicro1/jzhao399/scratch/log/pico/${PBS_JOBNAME}_${PBS_JOBID}.out
#PBS -e /nv/hmicro1/jzhao399/scratch/log/pico/${PBS_JOBNAME}_${PBS_JOBID}.err
#PBS -t 127,131,132,244,245,247,264-266,281,282,284,304,497,539,540,550-552


module load open64/4.5.1
module load bwa/0.7.4

source ~/.bashrc

conda init bash

conda activate base



name=pico${PBS_ARRAYID}
wd=/nv/hmicro1/jzhao399/scratch/18A.TAD80.bam
MAGs_dir=/nv/hmicro1/jzhao399/data/pico/12C_DAS_allbin_usearch64_drep/dereplicated_genomes
output=/nv/hmicro1/jzhao399/scratch/18A.TAD80.cov/${name}

for F in ${wd}/${name}/*.bam; do
	BASE=${F##*/}
	SAMPLE=${BASE%.*}
	bedtools genomecov -ibam $F -bga >> ${output}/${SAMPLE}.bedtools.cov.txt
done
