#!/bin/bash
#PBS -N MAG-abudance-coverm-make
#PBS -l mem=28gb
#PBS -l nodes=1:ppn=28
#PBS -l walltime=72:00:00
#PBS -q biocluster-6
#PBS -o /nv/hmicro1/jzhao399/scratch/log/pico/${PBS_JOBNAME}_${PBS_JOBID}.out
#PBS -e /nv/hmicro1/jzhao399/scratch/log/pico/${PBS_JOBNAME}_${PBS_JOBID}.err
#PBS -t 127,131,132,244,245,247,264-266,281,282,284,304,497,539,540,550-552


module load open64/4.5.1
module load bwa/0.7.4

source ~/.bashrc

conda init bash

conda activate base



name=pico${PBS_ARRAYID}
wd=/nv/hmicro1/jzhao399/gbrandt6/projects/pico/reads/06.megahitAssembly/${name}
reads_dir=/nv/hmicro1/jzhao399/gbrandt6/projects/pico/reads/05.trimmedFastA
output=/nv/hmicro1/jzhao399/scratch/06.megahit_bwa_mapping


~/data/miniconda3/bin/coverm make -o ${output}/${name} -r ${wd}/${name}.contigs.long.fa -t 28 --interleaved ${reads_dir}/${name}.CoupledReads.fasta -p bwa-mem
