#!/bin/bash
#PBS -N simka_pico
#PBS -l nodes=1:ppn=24
#PBS -l mem=160gb
#PBS -l walltime=48:00:00
#PBS -q inferno
#PBS -A GT-ktk3-CODA20
#PBS -o /storage/home/hcoda1/4/jzhao399/p-ktk3-0/rich_project_bio-konstantinidis/scripts/log/${PBS_JOBNAME}_${PBS_JOBID}.out
#PBS -e /storage/home/hcoda1/4/jzhao399/p-ktk3-0/rich_project_bio-konstantinidis/scripts/log/${PBS_JOBNAME}_${PBS_JOBID}.err

module purge
source ~/.bashrc
conda init bash
conda init bash
conda activate base
which perl
which diamond
#VARIABLES

wd=/storage/home/hcoda1/4/jzhao399/p-ktk3-0/rich_project_bio-konstantinidis/pico_new/01.resample_reads
cd ${wd}
~/p-ktk3-0/miniconda3/bin/simka -in ${wd}/sample.txt -out-tmp ${wd} -simple-dist -nb-cores 24 -max-memory 15000 -out ${wd}
