#!/bin/bash
#PBS -N pico-seqtk-reample
#PBS -l nodes=1:ppn=20
#PBS -l mem=100gb
#PBS -l walltime=24:00:00
#PBS -q inferno
#PBS -A GT-ktk3-CODA20
#PBS -o /storage/home/hcoda1/4/jzhao399/p-ktk3-0/rich_project_bio-konstantinidis/scripts/log/${PBS_JOBNAME}_${PBS_JOBID}.out
#PBS -e /storage/home/hcoda1/4/jzhao399/p-ktk3-0/rich_project_bio-konstantinidis/scripts/log/${PBS_JOBNAME}_${PBS_JOBID}.err
#PBS -t 127,131,132,244,245,247,264-266,281,282,284,304,497,539,540,550-552

name=pico${PBS_ARRAYID}
conda init bash
conda activate base
which seqtk
echo ${name}

output=/storage/home/hcoda1/4/jzhao399/p-ktk3-0/rich_project_bio-konstantinidis/pico_new/01.resample_reads

output2=/storage/home/hcoda1/4/jzhao399/p-ktk3-0/rich_project_bio-konstantinidis/pico_new/02.megahit
read_1=/storage/home/hcoda1/4/jzhao399/p-ktk3-0/gbrandt6/projects/pico/reads/03.trimmedFastQ/${name}_1P.fastq
read_2=/storage/home/hcoda1/4/jzhao399/p-ktk3-0/gbrandt6/projects/pico/reads/03.trimmedFastQ/${name}_2P.fastq
~/p-ktk3-0/miniconda3/bin/seqtk sample -s100 ${read_1} 37500000 > ${output}/${name}.resampled.R1.fq
~/p-ktk3-0/miniconda3/bin/pigz -p 20 ${output}/${name}.resampled.R1.fq
~/p-ktk3-0/miniconda3/bin/seqtk sample -s100 ${read_2} 37500000 > ${output}/${name}.resampled.R2.fq
~/p-ktk3-0/miniconda3/bin/pigz -p 20 ${output}/${name}.resampled.R2.fq
~/p-ktk3-0/miniconda3/bin/megahit -1 ${output}/${name}.resampled.R1.fa.gz -2 ${output}/${name}.resampled.R2.fa.gz -o ${output2}/${name} -t 20 --out-prefix ${name} --presets meta-large
