#!/bin/bash
#PBS -N centrifuge_download
#PBS -l nodes=1:ppn=20
#PBS -l mem=320gb
#PBS -l walltime=96:00:00
#PBS -q inferno
#PBS -A GT-ktk3-CODA20
#PBS -o /storage/home/hcoda1/4/jzhao399/p-ktk3-0/rich_project_bio-konstantinidis/scripts/log/${PBS_JOBNAME}_${PBS_JOBID}.out
#PBS -e /storage/home/hcoda1/4/jzhao399/p-ktk3-0/rich_project_bio-konstantinidis/scripts/log/${PBS_JOBNAME}_${PBS_JOBID}.err
source ~/.bashrc
conda init bash
conda activate base
conda activate centrifuge

which dustmasker
~/p-ktk3-0/miniconda3/envs/centrifuge/bin/dustmasker -h
cd ~/p-ktk3-0/rich_project_bio-konstantinidis/centrifuge_db
~/p-ktk3-0/miniconda3/envs/centrifuge/bin/centrifuge-build -p 20 --conversion-table seqid2taxid.map --taxonomy-tree taxonomy/nodes.dmp --name-table taxonomy/names.dmp input-sequences.fna abv
