#!/bin/bash
#PBS -N MetaPrism_20_db
#PBS -l nodes=1:ppn=20
#PBS -l mem=180gb
#PBS -l walltime=48:00:00
#PBS -q inferno
#PBS -A GT-ktk3-CODA20
#PBS -o /storage/home/hcoda1/4/jzhao399/p-ktk3-0/rich_project_bio-konstantinidis/scripts/log/${PBS_JOBNAME}_${PBS_JOBID}.out
#PBS -e /storage/home/hcoda1/4/jzhao399/p-ktk3-0/rich_project_bio-konstantinidis/scripts/log/${PBS_JOBNAME}_${PBS_JOBID}.err
#PBS -t 127,131,132,244,245,247,264-266,281,282,284,304,497,539,540,550-552

name=pico${PBS_ARRAYID}
module purge
source ~/.bashrc
conda init bash
conda init bash
conda activate base
conda activate centrifuge
which centrifuge
which perl
which diamond
index=~/p-ktk3-0/rich_project_bio-konstantinidis/centrifuge_db/abv
output=/storage/home/hcoda1/4/jzhao399/p-ktk3-0/rich_project_bio-konstantinidis/pico_new/03.MetaPrism_predicted
assembly=/storage/home/hcoda1/4/jzhao399/p-ktk3-0/rich_project_bio-konstantinidis/pico_new/02.megahit

~/p-ktk3-0/miniconda3/envs/centrifuge/bin/perl /storage/home/hcoda1/4/jzhao399/p-ktk3-0/rich_project_bio-konstantinidis/centrifuge_db/MetaPrism/MetaPrism_gene_prepare.pl -k
~/p-ktk3-0/miniconda3/envs/centrifuge/bin/perl /storage/home/hcoda1/4/jzhao399/p-ktk3-0/rich_project_bio-konstantinidis/centrifuge_db/MetaPrism/MetaPrism_gene.pl -p 20 ${output}/${name}.gene1 ${assembly}/${name}/${name}.contigs.fna /storage/home/hcoda1/4/jzhao399/p-ktk3-0/rich_project_bio-konstantinidis/pico_new/01.resample_reads/${name}.resampled_1.fastq.gz /storage/home/hcoda1/4/jzhao399/p-ktk3-0/rich_project_bio-konstantinidis/pico_new/01.resample_reads/${name}.resampled_2.fastq.gz
~/p-ktk3-0/miniconda3/envs/centrifuge/bin/perl /storage/home/hcoda1/4/jzhao399/p-ktk3-0/rich_project_bio-konstantinidis/centrifuge_db/MetaPrism/MetaPrism_taxon_centrifuge.pl -p 20 ${output}/${name}.gene1.region.abundance.txt ${assembly}/${name}/${name}.contigs.fna ${index} > ${output}/${name}_taxon.region1.abundance.txt
