#!/bin/bash
#PBS -N usearch_close_ref
#PBS -l nodes=1:ppn=24
#PBS -l mem=120gb
#PBS -l walltime=48:00:00
#PBS -q inferno
#PBS -A GT-ktk3-CODA20
#PBS -o /storage/home/hcoda1/4/jzhao399/p-ktk3-0/rich_project_bio-konstantinidis/scripts/log/${PBS_JOBNAME}_${PBS_JOBID}.out
#PBS -e /storage/home/hcoda1/4/jzhao399/p-ktk3-0/rich_project_bio-konstantinidis/scripts/log/${PBS_JOBNAME}_${PBS_JOBID}.err

module purge
source ~/.bashrc
conda init bash
conda activate base
which usearch11
which diamond
#VARIABLES

wd=/storage/home/hcoda1/4/jzhao399/p-ktk3-0/
~/p-ktk3-0/miniconda3/bin/usearch11 -closed_ref ${wd}/combined.16Sreads_clean1.fa -db ${wd}/SILVA_138.1_SSURef_tax_silva.fasta -otutabout ${wd}/Haibei.bac.usearch.otutab_silva_0.99.txt -strand both -id 0.99 -tabbedout ${wd}/Haibei.bac.usearch.closed_silva_0.99.txt -threads 24
