#!/bin/bash
#PBS -N MetaPrism_20_db
#PBS -l nodes=1:ppn=24
#PBS -l mem=120gb
#PBS -l walltime=48:00:00
#PBS -q inferno
#PBS -A GT-ktk3-CODA20
#PBS -o /storage/home/hcoda1/4/jzhao399/p-ktk3-0/rich_project_bio-konstantinidis/scripts/log/${PBS_JOBNAME}_${PBS_JOBID}.out
#PBS -e /storage/home/hcoda1/4/jzhao399/p-ktk3-0/rich_project_bio-konstantinidis/scripts/log/${PBS_JOBNAME}_${PBS_JOBID}.err
#PBS -t 127,131,132,244,245,247,264-266,281,282,284,304,497,539,540,550-552

name=pico${PBS_ARRAYID}
module purge
source ~/.bashrc
conda init bash
conda init bash
conda activate base
conda activate centrifuge
which centrifuge
which perl
which diamond
index=~/p-ktk3-0/rich_project_bio-konstantinidis/centrifuge_db/abv
output=/storage/home/hcoda1/4/jzhao399/p-ktk3-0/rich_project_bio-konstantinidis/pico_new/04.centrifuge
assembly=/storage/home/hcoda1/4/jzhao399/p-ktk3-0/rich_project_bio-konstantinidis/pico_new/02.megahit
~/p-ktk3-0/miniconda3/envs/centrifuge/bin/centrifuge -f -p 24 -x ${index} -U ${assembly}/${name}/${name}.contigs.long.fa -S ${output}/${name}.centrifuge.classification.txt --report-file ${output}/${name}.centrifuge.report
