#!/bin/bash
#PBS -N vamb-binning
#PBS -l nodes=1:ppn=24
#PBS -l mem=360gb
#PBS -l walltime=120:00:00
#PBS -q inferno
#PBS -A GT-ktk3-CODA20
#PBS -o /storage/home/hcoda1/4/jzhao399/p-ktk3-0/rich_project_bio-konstantinidis/scripts/log/${PBS_JOBNAME}_${PBS_JOBID}.out
#PBS -e /storage/home/hcoda1/4/jzhao399/p-ktk3-0/rich_project_bio-konstantinidis/scripts/log/${PBS_JOBNAME}_${PBS_JOBID}.err
#PBS -t 127,131,132,244,245,247,264-266,281,282,284,304,497,539,540,550-552

name=pico${PBS_ARRAYID}
module purge
module load cuda/10.1
source ~/.bashrc
conda init bash
conda activate base
which perl
which samtools
#VARIABLES
name=pico${PBS_ARRAYID}
wd=/storage/home/hcoda1/4/jzhao399/p-ktk3-0/rich_project_bio-konstantinidis/pico_new/01.resample_reads
output=/storage/home/hcoda1/4/jzhao399/p-ktk3-0/rich_project_bio-konstantinidis/pico_new/02.megahit/${name}
contig=/storage/home/hcoda1/4/jzhao399/p-ktk3-0/rich_project_bio-konstantinidis/pico_new/02.megahit/${name}/${name}.contigs.long.fa

### ~/p-ktk3-0/miniconda3/bin/samtools sort -@ 24 -O bam -o /storage/home/hcoda1/4/jzhao399/p-ktk3-0/rich_project_bio-konstantinidis/pico_new/02.megahit/${name}.sorted.bam /storage/home/hcoda1/4/jzhao399/p-ktk3-0/rich_project_bio-konstantinidis/pico_new/02.megahit/${name}.bam

#### ~/p-ktk3-0/miniconda3/bin/samtools index /storage/home/hcoda1/4/jzhao399/p-ktk3-0/rich_project_bio-konstantinidis/pico_new/02.megahit/${name}.sorted.bam /storage/home/hcoda1/4/jzhao399/p-ktk3-0/rich_project_bio-konstantinidis/pico_new/02.megahit/${name}.sorted.bam.bai
~/p-ktk3-0/miniconda3/bin/jgi_summarize_bam_contig_depths --outputDepth /storage/home/hcoda1/4/jzhao399/p-ktk3-0/rich_project_bio-konstantinidis/pico_new/02.megahit/${name}.depth.txt /storage/home/hcoda1/4/jzhao399/p-ktk3-0/rich_project_bio-konstantinidis/pico_new/02.megahit/${name}.sorted.bam
rm -rf ${output}/out


~/p-ktk3-0/miniconda3/bin/vamb --outdir ${output}/out --fasta ${contig} --jgi /storage/home/hcoda1/4/jzhao399/p-ktk3-0/rich_project_bio-konstantinidis/pico_new/02.megahit/${name}.depth.txt --minfasta 200000 
