#!/bin/bash
#PBS -N checkm_pico_vamb
#PBS -l mem=120gb
#PBS -l nodes=1:ppn=24
#PBS -l walltime=48:00:00
#PBS -q inferno
#PBS -A GT-ktk3-CODA20
#PBS -o /storage/home/hcoda1/4/jzhao399/p-ktk3-0/rich_project_bio-konstantinidis/scripts/log/${PBS_JOBNAME}_${PBS_JOBID}.out
#PBS -e /storage/home/hcoda1/4/jzhao399/p-ktk3-0/rich_project_bio-konstantinidis/scripts/log/${PBS_JOBNAME}_${PBS_JOBID}.err

module purge
source ~/.bash_profile
conda init bash
conda activate base

wd=/storage/home/hcoda1/4/jzhao399/p-ktk3-0/rich_project_bio-konstantinidis/pico_new/02.megahit/vamb_all_new/
~/p-ktk3-0/miniconda3/bin/checkm lineage_wf ${wd}/bins ${wd}/bins_checkm -x fna -t 24 --tab_table -f ${wd}/bins_checkm_qa.txt --pplacer_threads 8
