#!/bin/bash
#PBS -N kaamer-db-make
#PBS -l mem=120gb
#PBS -l nodes=1:ppn=24
#PBS -l walltime=120:00:00
#PBS -q inferno
#PBS -A GT-ktk3-CODA20
#PBS -o /storage/home/hcoda1/4/jzhao399/p-ktk3-0/rich_project_bio-konstantinidis/scripts/log/${PBS_JOBNAME}_${PBS_JOBID}.out
#PBS -e /storage/home/hcoda1/4/jzhao399/p-ktk3-0/rich_project_bio-konstantinidis/scripts/log/${PBS_JOBNAME}_${PBS_JOBID}.err

module purge
source ~/.bash_profile
conda init bash
conda activate base

~/p-ktk3-0/miniconda3/bin/kaamer-db -merge -dbs /storage/home/hcoda1/4/jzhao399/p-ktk3-0/rich_project_bio-konstantinidis/kaamer-db/kaamerdb-refseq-bacteria_splits -o /storage/home/hcoda1/4/jzhao399/p-ktk3-0/rich_project_bio-konstantinidis/kaamer-db/kaamerdb-refseq-bacteria.merged
~/p-ktk3-0/miniconda3/bin/kaamer-db -index -d /storage/home/hcoda1/4/jzhao399/p-ktk3-0/rich_project_bio-konstantinidis/kaamer-db/kaamerdb-refseq-bacteria.merged -t 24